name: Build and Release ASM EXE

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install NASM
      run: choco install nasm -y

    - name: Compile crash2.asm to OBJ
      run: nasm -f win64 crash2.asm -o crash2.obj

    - name: Link to EXE
      run: |
        gcc crash2.obj -o crash2.exe -lkernel32 -luser32

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: crash2-exe
        path: crash2.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: crash2-exe

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: crash2.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
