name: Build Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download Golink
        run: |
          Invoke-WebRequest `
            -Uri "https://github.com/achappell/Golink/releases/download/v1.0.5/golink.exe" `
            -OutFile "C:\golink.exe" `
            -Headers @{"Accept"="application/octet-stream"}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure project
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: build/Release/*
