name: Build and Release NASM 64-bit Crash System

on:
  push:
    tags:
      - 'v*'  # Trigger pada push tag yang dimulai dengan 'v'
  workflow_dispatch:  # Memungkinkan trigger manual

permissions:
  contents: write  # Diperlukan untuk membuat release

jobs:
  build-nasm-64bit:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup NASM
      run: |
        # Download dan install NASM
        Invoke-WebRequest -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip" -OutFile "nasm.zip"
        Expand-Archive -Path nasm.zip -DestinationPath nasm
        echo "C:\nasm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Setup GoLink (optional linker)
      run: |
        # Download GoLink
        Invoke-WebRequest -Uri "https://github.com/achappell/Golink/releases/download/v1.0.5/golink.exe" -OutFile "golink.exe"
        echo "C:\golink.exe" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Compile with NASM
      run: |
        nasm -f win64 crash2.asm -o crash.obj

    - name: Link with GoLink
      run: |
        golink /console /entry main crash.obj kernel32.dll user32.dll advapi32.dll gdi32.dll

    - name: Extract version from tag
      id: get_version
      run: |
        if ("${{ github.ref_type }}" -eq "tag") {
          $tag = "${{ github.ref_name }}"
          $version = $tag -replace '^v', ''
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "version=$version" >> $env:GITHUB_OUTPUT
        } else {
          echo "VERSION=dev" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "version=dev" >> $env:GITHUB_OUTPUT
        }

    - name: Rename binary with version
      run: |
        if ("${{ env.VERSION }}" -ne "dev") {
          Move-Item -Path crash.exe -Destination "crash-${{ env.VERSION }}-x64.exe"
        } else {
          $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
          Move-Item -Path crash.exe -Destination "crash-dev-$timestamp-x64.exe"
        }

    - name: Create checksum
      run: |
        if ("${{ env.VERSION }}" -ne "dev") {
          Get-FileHash -Path "crash-${{ env.VERSION }}-x64.exe" -Algorithm SHA256 | Select-Object -ExpandProperty Hash | Out-File -Encoding ASCII "crash-${{ env.VERSION }}-x64.sha256"
        } else {
          Get-FileHash -Path "crash-dev-*-x64.exe" -Algorithm SHA256 | Select-Object -ExpandProperty Hash | Out-File -Encoding ASCII "crash-dev-$timestamp-x64.sha256"
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: crash-system-${{ env.VERSION }}-x64
        path: |
          crash-*.exe
          crash-*.sha256
          crash.asm

    - name: Create release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Crash System ${{ github.ref_name }} (64-bit)
        body: |
           **WARNING: HIGHLY DESTRUCTIVE SOFTWARE** 
          
          64-bit NASM version. This release contains code that will:
          - Create intense visual and audio glitches
          - Overwrite the Master Boot Record (MBR)
          - Cause permanent system damage
          
          **ONLY USE IN CONTROLLED VIRTUAL ENVIRONMENTS**
          
          Version: ${{ github.ref_name }}
          Architecture: x64
          Build date: ${{ github.event.head_commit.timestamp }}
          SHA256: $(cat crash-${{ env.VERSION }}-x64.sha256)
        files: |
          crash-${{ env.VERSION }}-x64.exe
          crash-${{ env.VERSION }}-x64.sha256
          crash.asm
        draft: false
        prerelease: false
